### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by TotallyMonica** [TotallyMonica/CS533MobileApp#2]
- [x] Assign roles
  - [x] Project Leader
  - [x] Mobile Application Architect
  - [x] Mobile Application Developer
  - [x] Quality Assurance Specialist (Mobile Application Tester)
  - [x] Database Developer
  - [x] Data Scientist
  - [x] Security Specialist
- [x] Components
  - [x] Two activities
  - [x] Fragment
  - [x] JSON webservice (interpreting this as read/write JSON)
  - [x] Back-end database (writing as of 7/24, still need to read)
  - [x] Data Virtualization
- [ ] Powerpoint (See #3)
  - [ ] Project analysis
  - [ ] Alternative solution analysis
  - [ ] Project design
  - [ ] Project progress evaluation
  - [ ] Development
  - [ ] Integration and testing
  - [ ] Implementation
  - [ ] Evaluation and future work
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] Nice to haves
  - [ ] Make sure password resets work
